language: node_js

node_js: '10'

cache: yarn

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '10'
      script:
        - yarn run build
        - yarn run deploy

stages:
  - name: release
    if: branch = develop AND type = push AND fork = false
