language: node_js

node_js: '10'

cache: yarn

jobs:
  include:
    - stage: release
      language: node_js
      node_js: '10'
      script:
        - yarn run build
        - echo "yannickfricke.de" > dist/CNAME
        - yarn gh-pages --silent -d dist -b master -r https://$GH_TOKEN@github.com/YannickFricke/YannickFricke.github.io.git

stages:
  - name: release
    if: branch = develop AND type = push AND fork = false
