export enum Language {
    Bash = 'Bash',
    GIT = 'GIT',
    NodeJS = 'Node.JS',
    Gulp = 'Gulp',
    Webpack = 'Webpack',
    BrowserSync = 'BrowserSync',
    TypeScript = 'TypeScript',
    Commitizen = 'Commitizen',
    AutoPrefixer = 'AutoPrefixer',
    SCSS = 'SCSS',
    TMI = 'tmi.js',
    SocketIO = 'Socket.IO',
    React = 'React',
    ReactRouter = 'ReactRouter',
    Electron = 'Electron',
    Redux = 'Redux',
    Lerna = 'Lerna',
    SemanticRelease = 'semantic-release',
    TipeeeStream = 'TipeeeStream',
    Packagaya = 'Packagaya',
    Express = 'Express',
    InquirerJS = 'inquirer.js',
    Inversify = 'inversify',
    GitHub_Actions = 'GitHub Actions',
    Lodash = 'Lodash',
}
